{% set name = "anaconda-cli-base" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cli_base-{{ version }}.tar.gz
  sha256: e23cfa48030e896f301c03511e80cbef5a91a02da93e8d5d8e4198d0badea6c7  

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8,<3.12
    - click
    - readchar
    - rich
    - typer
    - pydantic-settings >=2.3
  run_constrained:
    # Ensure that a version of anaconda-cli-base cannot be installed if an incompatible
    # older version of anaconda-client is installed.
    - anaconda-client >=1.13.0

test:
  imports:
    - anaconda_cli_base
  commands:
    - python -c "from anaconda_cli_base import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
