{% set name = "anaconda-cli-base" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cli_base-{{ version }}.tar.gz
  sha256: 8c6fe10f844b2f4c3b70640e73862d079481b53b15eb54ab4e2cab0bc19be387

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.8
    - readchar
    - rich
    - typer

test:
  imports:
    - anaconda_cli_base
  commands:
    - python -c "from anaconda_cli_base import __version__; assert __version__ == \"{{ version }}\""

about:
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
